from datetime import datetime
from typing import Any


def generate_html_report(
    session_id: str,
    dependency: dict,
    third_party: dict,
    vitals: dict,
    anomalies: Any,
) -> str:
    now = datetime.utcnow().isoformat()

    def metric_row(name: str, data: dict) -> str:
        if not data:
            return ""
        status = "✅" if data.get("pass") else "❌"
        threshold = f" (threshold: {data.get('threshold', 'N/A')})" if "threshold" in data else ""
        return f"""
        <tr>
            <td style="padding:6px;border-bottom:1px solid #333">{name}</td>
            <td style="padding:6px;border-bottom:1px solid #333">{data.get('avg', 'N/A')}</td>
            <td style="padding:6px;border-bottom:1px solid #333">{data.get('p95', 'N/A')}</td>
            <td style="padding:6px;border-bottom:1px solid #333">{data.get('min', 'N/A')} – {data.get('max', 'N/A')}</td>
            <td style="padding:6px;border-bottom:1px solid #333">{status}{threshold}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Analysis Report — {session_id[:8]}</title>
<style>
  body {{ font-family: monospace; background: #0f172a; color: #e2e8f0; padding: 20px; }}
  h1 {{ color: #22d3ee; }}
  h2 {{ color: #a78bfa; border-bottom: 1px solid #334155; padding-bottom: 4px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
  th {{ text-align: left; padding: 6px; border-bottom: 2px solid #475569; color: #94a3b8; }}
  .card {{ background: #1e293b; border: 1px solid #334155; border-radius: 8px; padding: 16px; margin: 12px 0; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; }}
  .badge-red {{ background: #7f1d1d; color: #fca5a5; }}
  .badge-green {{ background: #14532d; color: #86efac; }}
  .badge-yellow {{ background: #713f12; color: #fcd34d; }}
</style>
</head><body>
<h1>📊 Observability Analysis Report</h1>
<p>Session: <code>{session_id}</code> | Generated: {now}</p>

<div class="card">
    <h2>🌐 Third-Party Classification</h2>
    <p>Total requests: {third_party.get('total_requests', 0)} | Third-party: <strong>{third_party.get('third_party_requests', 0)}</strong> ({third_party.get('percentage', 0)}%)</p>
    <table>
        <tr><th>Category</th><th>Count</th><th>Examples</th></tr>
"""
    for cat, data in third_party.get("categories", {}).items():
        examples = ", ".join(data.get("urls", [])[:3])
        html += f"<tr><td>{cat}</td><td>{data['count']}</td><td style='font-size:12px;color:#94a3b8'>{examples}</td></tr>"

    html += """</table></div>

<div class="card">
    <h2>⚡ Core Web Vitals</h2>
    <table><tr><th>Metric</th><th>Average</th><th>P95</th><th>Range</th><th>Status</th></tr>
"""
    for metric, data in vitals.items():
        html += metric_row(metric, data)

    html += """</table></div>

<div class="card">
    <h2>🕸️ Dependency Graph</h2>
"""
    if isinstance(dependency, dict):
        html += f"""<p>Nodes: {dependency.get('nodes', 0)} | Edges: {dependency.get('edges', 0)} | Density: {dependency.get('density', 0):.4f}</p>
<p>Third-party nodes: {len(dependency.get('third_parties', []))} | Components: {dependency.get('components', 0)}</p>
"""
    html += "</div>"

    if isinstance(anomalies, dict) and anomalies.get("anomalies_found", 0) > 0:
        html += f"""<div class="card">
    <h2>🚨 Anomaly Detection</h2>
    <p>Found <strong>{anomalies['anomalies_found']}</strong> anomalies out of {anomalies['total_requests']} requests</p>
    <table><tr><th>URL</th><th>Response Time</th><th>Size</th><th>Status</th><th>Score</th></tr>
"""
        for a in anomalies.get("anomalies", [])[:20]:
            feats = a.get("features", {})
            html += f"""<tr>
                <td style="font-size:12px">{a.get('url', '')[:60]}</td>
                <td>{feats.get('response_time_ms', 'N/A')}ms</td>
                <td>{feats.get('body_size_kb', 'N/A')}KB</td>
                <td>{feats.get('status', 'N/A')}</td>
                <td>{a.get('score', 'N/A')}</td>
            </tr>"""
        html += "</table></div>"

    html += """
<p style="color:#475569;font-size:12px;margin-top:40px">Generated by OBS Analysis Engine v2.0</p>
</body></html>"""
    return html
